### ISSUE TITLE
I want to remove the "<user> used a Workflow template to send this card. Get template" line

### ISSUE THREAD

**Issue by jellis206** [playwright-community/playwright-msteams-reporter#13]
I really don't need a whole line item about what Workflow template I used to distract from the message. I have been searching through the codebase as well as the powerautomate stuff to see if I could remove it, but have had no luck. It is sandwiched between the results table and the results link, which makes me think it is somehow being inserted into the adaptive card. If you can point me in the right direction I don't mind forking the repo and making the change myself.

I have outlined in red the line item I am talking about.
<img width="800" alt="Screenshot 2024-09-19 at 11 22 26" src="https://github.com/user-attachments/assets/e2f27364-2723-4e32-9de9-8f0247a2c212">

**Comment by estruyf** [comment]
Hi @jellis206, unfortunately, this is something Microsoft adds, so it is out of our control. That said, there seems to be a trick to get it removed. You can do this by creating a copy of the flow and using that one instead. You can find more details here: https://docs.hetrixtools.com/microsoft-teams-how-to-remove-name-used-a-workflow-template-to-send-this-card-get-template/

I've just tried it out, and it seems to work fine on my end.

**Comment by estruyf** [comment]
I've added the procedure to the README:

![image](https://github.com/user-attachments/assets/b93a6f91-2c60-4eef-bc3e-da1856fc8f03)

**Comment by jellis206** [comment]
Thank you! I was half expecting this to be ignored. I really appreciate the guidance!!
