### ISSUE TITLE
[Question] Regarding removal of incomming webhooks comming this 1st october

### ISSUE THREAD

**Issue by Az8th** [playwright-community/playwright-msteams-reporter#17]
Hello @estruyf,

It is stated in the readme that
> Microsoft Teams incoming webhook (retiring October 1, 2024)

As this will be due in 2 days, I propose to address this rapidly to encourage people still using it to switch to the Power Automate ones.

Should we then...

1. remove both the `webhookType` parameter and the logic behind using the `msteams` option completely ? (Users that will update the package would face an error as this parameter would not be recognized)
2. deprecate it and replace all the code used when it is set to `msteams` with a warning indicating this method no longer works ? (Less brutal and dedicated message, while no impact on `powerautomate` users, as it is set by default and therefore not mandatory to mention it in the config file)
3. same as option 2, minus deprecation, in case new methods may emerge later ?

Or chose another way ?

If needed, I can provide a PR that would respect your choice
Thanks again for the awesome work !

**Comment by estruyf** [comment]
Hi @Az8th, deprecation has been extended to December 2025, so we can leave it as is. Although I like the deprecation notice on the `msteams` webhook type property.
