### ISSUE TITLE
On using the webhook url , type as ms teams, in the config file, I'm getting Invalid url error

### ISSUE THREAD

**Issue by grajesh690** [playwright-community/playwright-msteams-reporter#18]
I'm getting invalid webhook url error, for the type msteams.

When tried as a POST request within the code / triggering via postman, I'm not seeing any issues.

**Comment by estruyf** [comment]
That probably has to do with the validation of the URL. Check the following file: https://github.com/playwright-community/playwright-msteams-reporter/blob/main/src/utils/validateWebhookUrl.ts

Can you validate it?

**Comment by grajesh690** [comment]
It shows me invalid ! any workaround for this ?

**Comment by estruyf** [comment]
Would you be able to share the URL? You can send it to: elio@struyfconsulting.be

Or another way is to use the Power Automate approach as that is future proof, the MS Teams webhook is deprecated.

**Comment by grajesh690** [comment]
I don't think so I can able to share. But based on the pattern, I noticed that https:\/\/[a-zA-Z]+. allows only alphabets, but my url contains numbers for eg:https://test9.webhook.office.com/webhookb2/

**Comment by estruyf** [comment]
Fix is coming up @grajesh690

**Comment by estruyf** [comment]
@grajesh690 could you validate with version: `playwright-msteams-reporter@0.0.12-beta.1140488`? This should include the fix, if it works, I'll release version `0.0.12`.

**Comment by grajesh690** [comment]
@estruyf  This works ! Thanks much it helps

**Comment by estruyf** [comment]
Release is out!
