### ISSUE TITLE
Enhancement: Add a failure link and text option

### ISSUE THREAD

**Issue by estruyf** [playwright-community/playwright-msteams-reporter#2]
Based on feedback from Discord, it would be useful to have the ability to add a link action when the tests fail.

- [x] Add a `linkUrlOnFailure` property
- [x] Add a `linkTextOnFailure` property
- [x] Add support into the Adaptive Card to visualize the button

**Comment by Az8th** [comment]
Thanks for adding it 😄

**Comment by estruyf** [comment]
@Az8th once we have control over the Playwright community org on NPM, I'll release the new version. Status: https://github.com/microsoft/playwright/pull/31579#discussion_r1671962149

**Comment by estruyf** [comment]
This has been released in version `0.0.7`.
