### ISSUE TITLE
[Question] Send notification after running tests on multiple jobs

### ISSUE THREAD

**Issue by OlesNikon** [playwright-community/playwright-msteams-reporter#20]
Hello @estruyf,
I'm using the `playwright-msteams-reporter` to send test reports to Microsoft Teams as part of my CI workflow. To optimize test execution time, I want to run Playwright tests across multiple parallel jobs (shards). After all test jobs have completed, I’d like to send a single, consolidated report to MS Teams.

Is it possible to configure `playwright-msteams-reporter ` to aggregate reports from multiple jobs and send a unified notification to Teams?

**Comment by estruyf** [comment]
Hi @OlesNikon, I believe you should be able to gather all shards and run the `npx playwright merge-reports` with a configuration file like this:

```bash
npx playwright merge-reports --config=merge.config.ts ./blob-reports
```

The config (merge.config.ts):

```typescript
import type { MsTeamsReporterOptions } from "playwright-msteams-reporter";

export default {
  testDir: "./tests",
  reporter: [
    [
      'playwright-msteams-reporter',
      <MsTeamsReporterOptions>{
        webhookUrl: <webhook URL>,
        title: "Merged E2E Test Results",
        debug: true,
      },
    ],
  ],
};
```

I've verified it locally, can you check it on your end?

**Comment by OlesNikon** [comment]
@estruyf Thank you. It works
