### ISSUE TITLE
Results are duplicated

### ISSUE THREAD

**Issue by rpiwnicki** [playwright-community/playwright-msteams-reporter#3]
I have a problem because every time I get a result, it also contains the result of every previous execution. 

`    reporter: process.env.CI
        ? [['html'], ['junit', { outputFile: './playwright-report/junit-report.xml' }], ['github']]
        : [
              ['html'],
              [
                  'playwright-msteams-reporter',
                  {
                      webhookUrl:
                          'LINK',
                      webhookType: 'powerautomate',  // or "msteams"
                  },
              ],
          ],`

I don't use Chanel to send messages, only Group Chat on Teams, if that makes any difference. 
I run tests manually on my computer, not through CI. 

![image](https://github.com/playwright-community/playwright-msteams-reporter/assets/170719381/2ebc35e5-cdcd-41c9-91c9-f514839c3325)

**Comment by rvpv** [comment]
Ok, problem does not occur as the test is run in Github Actions.

**Comment by estruyf** [comment]
Thanks, @rpiwnicki, for opening an issue. I found out why it is happening, and I will implement a fix for it.

The new version's release will have to be postponed. We are working to access the Playwright community org on NPM, which will be the dependency's new home.

**Comment by estruyf** [comment]
This has been fixed in version `0.0.7`.
