### ISSUE TITLE
[Suggestion] Add colorblind support

### ISSUE THREAD

**Issue by Az8th** [playwright-community/playwright-msteams-reporter#5]
Hi,
Having color to differenciate rows is already very nice to enhance user experience, but I does not profit to colorblind people.
Then, I suggest to add emojis to test results types, such as those seen in the Playwright HTML report.
Example: 
✅ for passed
❌ for failed
⏭️ for skipped
⚠️for flaky

Adding one next to the title or subtitle to improve test suite status visibilty would be perfect.
It would profit to everyone by enhancing visibility.

If that seems leggit to you, I am lean to do the corresponding PR

Thanks and have a nice day

**Comment by estruyf** [comment]
Included the `enableEmoji` property which allows you to enable the emoji usage for test statuses.

You can test it out in version: `playwright-msteams-reporter@0.0.8-beta.9974841`

**Comment by estruyf** [comment]
Released in version `0.0.8`
