### ISSUE TITLE
[Bug] Webhook falsely consired invalid

### ISSUE THREAD

**Issue by Az8th** [playwright-community/playwright-msteams-reporter#7]
Hello, sorry for opening yet another issue

It seems webhooks starting with https://prod2-XX are considered invalid.
Could you please update the validation check to support them ?

(Observed in v0.0.8)

Thanks and have a nice day :D

**Comment by estruyf** [comment]
Fix is included in version `0.0.9`.

**Comment by Az8th** [comment]
Is this the world record for a closed issue ? 🤣

**Comment by estruyf** [comment]
Hahaha 🤪
